### ISSUE TITLE
DuplicateReporter can return duplicate accessions map with a null key leading to an NPE without explicit cause

### ISSUE THREAD

**Issue by jweiser** [reactome/data-release-pipeline#107]
In the DuplicateReporter class, it is possible for the `getDuplicateAccessions()` method to return a map which contains a `null` as a key if more than one GO instance has an unfilled accession:

https://github.com/reactome/data-release-pipeline/blob/develop/go-update/src/main/java/org/reactome/release/goupdate/DuplicateReporter.java#L52

If this case occurs, an exception to check the database for GO instances with null accessions would be helpful.  If possible, listing all the GO instances (db id, display name, and class) in the database with null accessions would be even better.

**Comment by SolomonShorser-OICR** [comment]
Ideally, the _database_ would enforce this with a `NOT NULL` constraint. Oh well, we can dream...

**Comment by SolomonShorser-OICR** [comment]
@jweiser Does this issue need to remain open? If it's still a problem in the stand-alone GO Update repository, could you please recreate this issue there? https://github.com/reactome/release-go-update/

**Comment by jweiser** [comment]
Yeah, I think this still need might need to be checked.  I've recreated the issue: https://github.com/reactome/release-go-update/issues/16
