### ISSUE TITLE
Definition for the GO term requested to be included in the new GO Molecular Function terms report

### ISSUE THREAD

**Issue by jweiser** [reactome/data-release-pipeline#112]
For the _new GO Molecular Function terms_ report, Bijay has requested that the definition of the GO term be included.

I believe the change needs to be made in this method:

https://github.com/reactome/data-release-pipeline/blob/develop/go-update/src/main/java/org/reactome/release/goupdate/GoTermsUpdater.java#L501

**Comment by SolomonShorser-OICR** [comment]
Now exists in the stand-alone GO Update repo, so I'm closing this issue.

For future work, see:
https://github.com/reactome/release-go-update/issues/15
