### ISSUE TITLE
OpenSet references can be removed from orthoinference code

### ISSUE THREAD

**Issue by jweiser** [reactome/data-release-pipeline#15]
The OpenSet subclass has now been removed from the data schema and so no longer needs to be handled by inferences.

**Comment by cookersjs** [comment]
This change has been made.

see a680538956eec45dfcc6b1a0c3d12eadf2882685 for OrthologousEntity change 
see 5ac72de77ca3ea06f971e2b82e55229a5b2fd061 for InstanceUtilities change
