### ISSUE TITLE
Gene Ontology is requesting a gzipped copy of gene_association.reactome in our download directory

### ISSUE THREAD

**Issue by jweiser** [reactome/data-release-pipeline#33]
In the DownloadDirectory project in Main.java, there is logic to copy the gene_association.reactome file to the new download directory.

We need to gzip the file so GO can process the file in their pipeline.  The final link will be:

https://www.reactome.org/download/current/gene_association.reactome.gz

**Comment by cookersjs** [comment]
DownloadDirectory zips the file as of release 69
