### ISSUE TITLE
GO:0070035 is obsolete

### ISSUE THREAD

**Issue by dvklopfenstein** [reactome/data-release-pipeline#41]
# Reactome DAG, version 68, contains this GO:0070035, which is obsolete

## 1) Here is GO:0070035 in Reactome, version 68:
```
MATCH (go:GO_Term{accession:"0070035"}) RETURN go
```

![image](https://user-images.githubusercontent.com/7278188/55522808-8596b980-5654-11e9-9148-a72b854ed865.png)

## 2) Here is GO:0070035 info in the go-basic.obo:

```
format-version: 1.2
data-version: releases/2019-03-19
```

```
[Term]
id: GO:0070035
name: obsolete purine NTP-dependent helicase activity
namespace: molecular_function
def: "OBSOLETE Catalysis of the reaction: purine NTP + H2O = purine NDP + phosphate, to drive the unwinding of a DNA or RNA helix." [GOC:mah]
comment: The reason for obsoletion is that helicases only and always use ATP (although under very specific experimental conditions GTP can perhaps be used; this is not the case in vivo), therefore this term was an unnecessary grouping term.
is_obsolete: true
```

**Comment by SolomonShorser-OICR** [comment]
Hi @dvklopfenstein !
Reactome releases data on a quarterly basis. GO data was updated for Release 68 back in mid-February. If these changes from GO are from mid-March, they should be picked up in the next Reactome release (69), a few months from now.
