### ISSUE TITLE
README for go-update in configuration section "pathToGOFile" needs to be updated

### ISSUE THREAD

**Issue by jweiser** [reactome/data-release-pipeline#71]
The README at https://github.com/reactome/data-release-pipeline/tree/feature/data-model-changes-for-GO/go-update needs to update the following line in the "Configuration" section:

**pathToGOFile=src/main/resources/gene_ontology_ext.obo**

The file name should now be go.obo.  This is now the name of the file from GO's website here http://current.geneontology.org/ontology/go.obo

**Comment by SolomonShorser-OICR** [comment]
See: https://github.com/reactome/data-release-pipeline/commit/1b820b5794156027725138848a7085d5a2fa9838
