### ISSUE TITLE
GO Update: Separate Instance Edits for each kind of modification

### ISSUE THREAD

**Issue by jweiser** [reactome/data-release-pipeline#77]
In the latest GO Update (v70 on August 9th, 2019), we saw instances updated by the GO Update have the same instance edit applied to the modification slot multiple times.  

E.g. 9658105 in the modified slot of http://curator.reactome.org/cgi-bin/instancebrowser?DB=gk_central&ID=868625&

This is due to different kinds of modification being done to instances during the update.  It would be great to have separate instance edits with descriptive notes used for each kind of modification and applied when the modification is done on any given instance.  This would also allow us to see the collection of instances modified in a specific way and if any given instance did or didn't get an expected kind of modification.

**Comment by cookersjs** [comment]
Since InstanceEdits have a note attribute, would it make sense to append changes to the note attribute and then at the end of it apply just the single InstanceEdit to the modification attribute?

**Comment by jweiser** [comment]
I think we were doing it that way with the Perl implementation of using one instance edit for any and all modifications.  The note was more generic though and didn't give much information about what was updated.

Using separate instance edits for each modification, though, might be more useful.  That way the changes are categorized.  Having an accurate note with a single instance edit is tricky because the instance edit will be shared among instances that may have had one or more modifications and not always the same kind.

**Comment by SolomonShorser-OICR** [comment]
That might work in some cases. Past and current use of InstanceEdits has a single IE object being used for _all_ operations of the same kind for a step. Which is a bit too broad. On the other hand, a new instance of an IE for _every_ single database operation might bloat the database too much. Might not be too serious for GO Update, but OrthoInference or AddLinks would probably create a significant amount of data in this way.

I was thinking of having a _pool_ of IEs, by type, such as "Create new [whatever]", "Update (name|description|other_field) from GO file", "Update references to GO objects", "Clear reference to deleted object" (in the note field)... and then use the correct IE from the pool.

**Comment by jweiser** [comment]
> That might work in some cases. Past and current use of InstanceEdits has a single IE object being used for _all_ operations of the same kind for a step. Which is a bit too broad. On the other hand, a new instance of an IE for _every_ single database operation might bloat the database too much. Might not be too serious for GO Update, but OrthoInference or AddLinks would probably create a significant amount of data in this way.
> 
> I was thinking of having a _pool_ of IEs, by type, such as "Create new [whatever]", "Update (name|description|other_field) from GO file", "Update references to GO objects", "Clear reference to deleted object" (in the note field)... and then use the correct IE from the pool.

A pool of common IEs to choose from sounds good so the number is still small but more informative and allows us to see which instance belongs to which IE.

**Comment by SolomonShorser-OICR** [comment]
FYI: Here's what it looks like now in the stand-alone GO Update repo:

https://github.com/reactome/release-go-update/blob/4a51cab364251fa5d7807a2fd74f1ce8fe3740b3/src/main/java/org/reactome/release/goupdate/GoUpdateInstanceEditUtils.java

@jweiser Is there any reason to keep this issue open any longer?

**Comment by jweiser** [comment]
> FYI: Here's what it looks like now in the stand-alone GO Update repo:
> 
> https://github.com/reactome/release-go-update/blob/4a51cab364251fa5d7807a2fd74f1ce8fe3740b3/src/main/java/org/reactome/release/goupdate/GoUpdateInstanceEditUtils.java
> 
> @jweiser Is there any reason to keep this issue open any longer?

No, the code in the stand-alone GO Update repo looks good.  I'll close this issue.
