### ISSUE TITLE
New Download File - Human Pathways with Diagrams (tab-delimited data)

### ISSUE THREAD

**Issue by jweiser** [reactome/data-release-pipeline#89]
Karen has requested a new file produced at release time for internal use.  The file would be tab-delimited and for all human pathways that have their own diagram (defined as a pathway used in a Pathway Diagram instance's "representedPathway" attribute slot) in the release database, the following columns would be output:

"Pathway DB ID"
"Pathway Name"
"Is Disease" (with values 'true' or 'false')

**Comment by cookersjs** [comment]
This has been done, as of #99
